name: 🚀 Install composer dependencies and migrate changes
on:
  push:
    branches:
      - main

env:
  FIRST_NAME: AMPDC
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull changes and install dependencies via composer.phar
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd website_AMPDC
            ${{ secrets.FUN_GIT_PULL }}
            php composer.phar install
            php artisan statamic:install
          host: ${{ secrets.SSH_SERVER }}
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          #          pass: ${{ secrets.SSH_PASS_KEY }}
          args: "-tt -vvv"
